version: '3'
services:
  db:
    container_name: bdformulario
    image: mysql
    environment:
      MYSQL_USER: formulario
      MYSQL_PASSWORD: pswformulario
      MYSQL_DATABASE: formularioDB
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"