version: '3'
services:
  db:
    container_name: bdporfolio
    image: mariadb
    environment:
      MARIADB_USER: porfolio
      MARIADB_PASSWORD: pswporfolio
      MARIADB_DATABASE: porfolioDB
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"