version: '3'
services:
  db:
    container_name: bdformulario
    image: mysl
    environment:
      MYSQL_USER: formulario01
      MYSQL_PASSWORD: pswformulario
      MYSQL_DATABASE: formulariocontacto
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"